{% set name = "starlite" %}
{% set version = "1.48.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starlite-{{ version }}.tar.gz
  sha256: 2a79e219d8f6498f2b9cad284615b58186c2043010dee70cefb62b930528efed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - anyio >=3
    - httpx >=0.22
    - msgspec >=0.10.1
    - multidict >=6.0.2
    - orjson
    - pydantic
    - pydantic_factories
    - pydantic-openapi-schema
    - python >=3.8,<4.0
    - pyyaml
    - typing-extensions

test:
  imports:
    - starlite
  commands:
    - pip check
  requires:
    - picologging
    - pip

about:
  home: https://github.com/starlite-api/starlite
  doc_url: https://starlite-api.github.io/starlite/
  summary: Light-weight and flexible ASGI API Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
