{% set name = "starlite" %}
{% set version = "1.46.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starlite-{{ version }}.tar.gz
  sha256: 9939dd0622191a80efc16a0e5ef83690cf362b906a36721b467e62219d591599

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - starlite=starlite.cli:cli

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - anyio >=3
    # For CLI
    - click >=8.1.3
    - httpx >=0.22
    - msgspec >=0.11.0
    - multidict >=6.0.2
    - pydantic
    - pydantic_factories
    - pydantic-openapi-schema >=1.5.0
    - python >=3.8,<4.0
    - pyyaml
    # For CLI
    - rich >=12.6.0
    - typing-extensions

test:
  imports:
    - starlite
  commands:
    - pip check
    - starlite --help
  requires:
    - picologging
    - pip

about:
  home: https://github.com/starlite-api/starlite
  doc_url: https://starlite-api.github.io/starlite/
  summary: Light-weight and flexible ASGI API Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
