{% set name = "starlite" %}
{% set version = "1.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starlite-{{ version }}.tar.gz
  sha256: b871551ba9ae448b9477a218e663e6fab4846b60f03c2a090997d5ddbe564a70

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - orjson
    - pydantic
    - pydantic_factories
    - pydantic-openapi-schema
    - python >=3.7,<4.0
    - pyyaml
    - starlette
    - starlite-multipart >=1.2.0
    - typing-extensions

test:
  imports:
    - starlite
  commands:
    - pip check
  requires:
    - picologging
    - pip

about:
  home: https://github.com/starlite-api/starlite
  doc_url: https://starlite-api.github.io/starlite/
  summary: Light-weight and flexible ASGI API Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
